module serpent:
    snakefile: "/home/jb/development/serpent/workflow/Snakefile"

BFILES={k: f"{config['data']['act']}/{k}/CleanedGenotypes/{v}" for k, v in config["bfiles"].items()}
A3_COHORTS=[item for item in list(BFILES.keys()) if item != "ACT1"]

A1_BFILE=f"{config['data']['act']}/ACT1/CleanedGenotypes/{config['bfiles']['ACT1']}"
rule get_missnp:
    container: config["images"]["plink"]
    input:
        act1_bed=f"{A1_BFILE}.bed",
        act1_bim=f"{A1_BFILE}.bim",
        act1_fam=f"{A1_BFILE}.fam",
        act3_bed=lambda wildcards: f"{BFILES[wildcards.act3_cohort]}.bed",
        act3_bim=lambda wildcards: f"{BFILES[wildcards.act3_cohort]}.bim",
        act3_fam=lambda wildcards: f"{BFILES[wildcards.act3_cohort]}.fam",
    output:
        missnp=temp("temp/{act3_cohort}-merge.missnp"),
    log: "logs/get_missnp/{act3_cohort}.log"
    params:
        act3_prefix=lambda wildcards: f"{BFILES[wildcards.act3_cohort]}",
    shell:
        """
        outdir=plink-missnp-{wildcards.act3_cohort}
        pfx=$outdir/plink
        mkdir -p $outdir
        plink --bed {input.act1_bed} \
              --bim {input.act1_bim} \
              --fam {input.act1_fam} \
              --bmerge {params.act3_prefix} \
              --make-bed \
              --out $pfx || \
            true
        mv ${{pfx}}-merge.missnp {output.missnp}
        mv $pfx.log {log}
        rm -rf $outdir
        """

rule combine_missnp:
    container: config["images"]["shiny_verse"]
    input:
        missnp=expand("temp/{act3_cohort}-merge.missnp", act3_cohort=A3_COHORTS),
    output:
        missnp="results/multiallelic_snps.txt",
    log: "logs/combine_missnp.log"
    script: "scripts/combine_missnp.R"


rule filter_missnp:
    container: config["images"]["plink"]
    input:
        bed=lambda wildcards: f"{BFILES[wildcards.cohort]}.bed",
        bim=lambda wildcards: f"{BFILES[wildcards.cohort]}.bim",
        fam=lambda wildcards: f"{BFILES[wildcards.cohort]}.fam",
        missnp="results/multiallelic_snps.txt",
    output:
        bed=temp("temp/{cohort}_filtered.bed"),
        bim=temp("temp/{cohort}_filtered.bim"),
        fam=temp("temp/{cohort}_filtered.fam"),
    log: "logs/filter_missnp/{cohort}.log"
    shell:
        """
        outdir=filtered-{wildcards.cohort}
        mkdir -p $outdir
        pfx=$outdir/plink
        plink --bed {input.bed} \
              --bim {input.bim} \
              --fam {input.fam} \
              --exclude {input.missnp} \
              --make-bed \
              --out $pfx
        mv $pfx.bed {output.bed}
        mv $pfx.bim {output.bim}
        mv $pfx.fam {output.fam}
        mv $pfx.log {log}
        rm -rf $outdir
        """

# TO-DO: use correct outputs/wildcards in shell directive
rule merge_bed:
    container: config["images"]["plink"]
    input:
        bed=expand("temp/{cohort}_filtered.bed", cohort=list(BFILES.keys())),
        bim=expand("temp/{cohort}_filtered.bim", cohort=list(BFILES.keys())),
        fam=expand("temp/{cohort}_filtered.fam", cohort=list(BFILES.keys())),
    output:
        bed=temp("temp/merged.bed"),
        bim=temp("temp/merged.bim"),
        fam=temp("temp/merged.fam"),
    log: "logs/merge_bed.log"
    shell:
        """
        outdir=bmerge-gt
        mkdir -p $outdir
        mergelist=$outdir/mergelist.txt
        pfx=$outdir/plink
        echo '{input.bed} ' | sed 's/\\.bed /\\n/g' > $mergelist
        plink \
        --merge-list $mergelist \
        --make-bed \
        --out $pfx
        mv $pfx.bed {output.bed}
        mv $pfx.bim {output.bim}
        mv $pfx.fam {output.fam}
        mv $pfx.log {log}
        rm -rf $outdir
        """

use rule convert_to_gds from serpent as serpent_convert_to_gds with:
    container: config["images"]["genesis"]
    input:
        bed_fn="temp/merged.bed",
        bim_fn="temp/merged.bim",
        fam_fn="temp/merged.fam",
    log: "logs/convert_to_gds.log"
    threads: 30
    output:
        gds="results/act_genotyped.gds",
